//
//  SystemSound+ID.swift
//  SystemSound
//
//  Created by otake on 2025/05/07.
//

import Foundation
import AudioToolbox

extension SystemSound {
    var id: Int {
        switch self {
        case .ringback_tone_ansi: return 30
        case .ringback_tone_cept: return 31
        case .busy_tone_ansi: return 32
        case .busy_tone_cept: return 33
        case .call_waiting_tone_ansi: return 34
        case .call_waiting_tone_cept: return 35
        case .end_call_tone_cept: return 36
        case .ringback_tone_hk: return 37
        case .ringback_tone_aus: return 38
        case .ringback_tone_uk: return 39
        case .new_mail: return 1000
        case .mail_sent: return 1001
        case .sms_received1: return 1002
        case .ReceivedMessage: return 1003
        case .SentMessage: return 1004
        case .alarm: return 1005
        case .low_power: return 1006
        case .sms_received2: return 1008
        case .sms_received3: return 1009
        case .sms_received4: return 1010
        case .sms_received5: return 1013
        case .sms_received6: return 1014
        case .tweet_sent: return 1016
        case .Swish: return 1018
        case .Anticipate: return 1020
        case .Bloom: return 1021
        case .Calypso: return 1022
        case .Choo_Choo: return 1023
        case .Descent: return 1024
        case .Fanfare: return 1025
        case .Ladder: return 1026
        case .Minuet: return 1027
        case .News_Flash: return 1028
        case .Noir: return 1029
        case .Sherwood_Forest: return 1030
        case .Spell: return 1031
        case .Suspense: return 1032
        case .Telegraph: return 1033
        case .Tiptoes: return 1034
        case .Update: return 1036
        case .ussd: return 1050
        case .SIMToolkitCallDropped: return 1051
        case .SIMToolkitGeneralBeep: return 1052
        case .SIMToolkitNegativeACK: return 1053
        case .SIMToolkitPositiveACK: return 1054
        case .SIMToolkitSMS: return 1055
        case .Tink: return 1057
        case .WebcamStart: return 1060
        case .ct_busy: return 1070
        case .ct_congestion: return 1071
        case .ct_path_ack: return 1072
        case .ct_error: return 1073
        case .ct_call_waiting: return 1074
        case .ct_keytone2: return 1075
        case .lock: return 1100
        case .key_press_click: return 1104
        case .Tock: return 1105
        case .connect_power: return 1106
        case .RingerChanged: return 1107
        case .photoShutter: return 1108
        case .shake: return 1109
        case .jbl_begin: return 1110
        case .jbl_confirm: return 1111
        case .jbl_cancel: return 1112
        case .begin_record: return 1113
        case .end_record: return 1114
        case .jbl_ambiguous: return 1115
        case .jbl_no_match: return 1116
        case .camera_shutter_burst: return 1119
        case .airdrop_invite: return 1120
        case .camera_shutter_burst_begin: return 1121
        case .camera_shutter_burst_end: return 1122
        case .focus_change_keyboard: return 1124
        case .focus_change_app_icon: return 1125
        case .focus_change_large: return 1126
        case .focus_change_small: return 1127
        case .navigation_push: return 1128
        case .navigation_pop: return 1129
        case .keyboard_press_normal: return 1130
        case .keyboard_press_delete: return 1131
        case .keyboard_press_clear: return 1132
        case .vc_invitation_accepted: return 1150
        case .vc_ringing: return 1151
        case .vc_ended: return 1152
        case .key_press_delete: return 1155
        case .key_press_modifier: return 1156
        case .wheels_of_time: return 1157
        case .go_to_sleep_alert: return 1158
        case .warsaw: return 1159
        case .nfc_scan_complete: return 1160
        case .access_scan_complete: return 1163
        case ._3rd_party_critical: return 1165
        case .PaymentReceived: return 1166
        case .Doorbell: return 1167
        case .PaymentReceivedFailure: return 1168
        case .dtmf_0: return 1200
        case .dtmf_1: return 1201
        case .dtmf_2: return 1202
        case .dtmf_3: return 1203
        case .dtmf_4: return 1204
        case .dtmf_5: return 1205
        case .dtmf_6: return 1206
        case .dtmf_7: return 1207
        case .dtmf_8: return 1208
        case .dtmf_9: return 1209
        case .dtmf_star: return 1210
        case .dtmf_pound: return 1211
        case .DeviceShutdown: return 1253
        case .long_low_short_high: return 1254
        case .short_double_high: return 1255
        case .short_low_high: return 1256
        case .short_double_low: return 1257
        case .middle_9_short_double_low: return 1259
        case .camera_timer_final_second: return 1260
        case .camera_timer_countdown: return 1261
        case .health_notification: return 1262
        case .MultiwayJoin: return 1263
        case .MultiwayLeave: return 1264
        case .multiway_invitation: return 1265
        case .PushToTalkJoined: return 1270
        case .PushToTalkLeft: return 1271
        case .PushToTalkUnmute: return 1272
        case .PushToTalkMute: return 1273
        case .PushToTalkUnmuteFail: return 1274
        case .SenderConfirmation: return 1275
        case .ReceiverConfirmation: return 1276
        case .ReceiverConnect: return 1277
        case .Typewriters: return 1335
        case .PINEnterDigit_AX: return 1340
        case .PINDelete_AX: return 1341
        case .PINSubmit_AX: return 1342
        case .PINUnexpected: return 1343
        case .PINEnterDigit: return 1344
        case .PINDelete: return 1345
        case .HeadphoneAudioExposureLimitExceeded: return 1362
        case .HealthNotificationUrgent: return 1363
        case .MicMute: return 1364
        case .MicUnmute: return 1365
        case .MicUnmuteFail: return 1366
        case .ScreenSharingStarted: return 1367
        case .MediaPaused: return 1368
        case .MediaHandoff: return 1369
        case .NavigationGenericManeuver: return 1370
        case .ScreenCapture: return 1393
        case .payment_success: return 1394
        case .payment_failure: return 1395
        case .acknowledgment_sent: return 1396
        case .acknowledgment_received: return 1397
        case .nfc_scan_failure: return 1398
        case .Notification_Haptic: return 1400
        case .Ringtone_US_Haptic: return 1401
        case .Ringtone_UK_Haptic: return 1402
        case .Alarm_Haptic: return 1403
        case .SiriStart_Haptic: return 1404
        case .SiriStopSuccess_Haptic: return 1405
        case .SiriStopFailure_Haptic: return 1406
        case .Stockholm_Haptic: return 1407
        case .Beat_Haptic: return 1408
        case .DoNotDisturb_Haptic: return 1410
        case .Timer_Haptic: return 1413
        case .NavigationLeftTurn_Haptic: return 1414
        case .NavigationRightTurn_Haptic: return 1415
        case .Detent_Haptic: return 1416
        case .NavigationGenericManeuver_Haptic: return 1417
        case .CameraCountdownTick_Haptic: return 1418
        case .CameraCountdownImminent_Haptic: return 1419
        case .ET_RemoteTap_Receive_Haptic: return 1420
        case .ET_RemoteTap_Send_Haptic: return 1421
        case .ET_BeginNotification_Haptic: return 1422
        case .StockholmActive_Haptic: return 1424
        case .StockholmActiveSingleCycle_Haptic: return 1425
        case .StockholmFailure_Haptic: return 1426
        case .SedentaryTimer_Haptic: return 1427
        case .HourlyChime_Haptic: return 1428
        case .Preview_AudioAndHaptic: return 1429
        case .Alert_ActivityGoalAttained_Haptic: return 1430
        case .Alert_ActivityGoalBehind_Haptic: return 1431
        case .Alert_ActivityGoalClose_Haptic: return 1432
        case .Alert_BatteryLow_10p_Haptic: return 1433
        case .Alert_BatteryLow_5p_Haptic: return 1434
        case .Alert_Calendar_Haptic: return 1435
        case .Alert_PassbookBalance_Haptic: return 1440
        case .Alert_PassbookGeofence_Haptic: return 1441
        case .Alert_PhotostreamActivity_Haptic: return 1442
        case .Alert_ReminderDue_Haptic: return 1443
        case .Alert_WalkieTalkie_Haptic: return 1445
        case .BatteryMagsafe_Haptic: return 1446
        case .BuddyPairingFailure_Haptic: return 1447
        case .BuddyPairingSuccess_Haptic: return 1448
        case .CameraShutter_Haptic: return 1449
        case .Alert_MapsDirectionsInApp_Haptic: return 1450
        case .MessagesIncoming_Haptic: return 1451
        case .MessagesOutgoing_Haptic: return 1452
        case .OnOffPasscodeFailure_Haptic: return 1453
        case .OrbLayers_Haptic: return 1458
        case .PhoneHangUp_Haptic: return 1459
        case .PhotosZoomDetent_Haptic: return 1460
        case .QB_Dictation_Haptic: return 1461
        case .StopwatchLap_Haptic: return 1464
        case .StopwatchReset_Haptic: return 1465
        case .StopwatchStart_Haptic: return 1466
        case .StopwatchStop_Haptic: return 1467
        case .TimerCancel_Haptic: return 1468
        case .TimerPause_Haptic: return 1469
        case .TimerStart_Haptic: return 1470
        case .TimerWheelHoursDetent_Haptic: return 1471
        case .WalkieTalkieActiveStart_Haptic: return 1472
        case .WorkoutComplete_Haptic: return 1473
        case .WorkoutCountdown_Haptic: return 1474
        case .Alert__3rdParty_Haptic: return 1475
        case .WorkoutSelect_Haptic: return 1476
        case .WorkoutPressStart_Haptic: return 1477
        case .TimerWheelMinutesDetent_Haptic: return 1479
        case .PhoneAnswer_Haptic: return 1480
        case .PhoneHold_Haptic: return 1481
        case .WalkieTalkieActiveEnd_Haptic: return 1482
        case .UISwitch_On_Haptic: return 1484
        case .UISwitch_Off_Haptic: return 1485
        case .UISwipe_Haptic: return 1486
        case .SystemStartup_Haptic: return 1487
        case .BuddyPairingRemoteConnection_Haptic: return 1488
        case .BuddyPairingRemoteTap_Haptic: return 1489
        case .QB_Dictation_Off_Haptic: return 1490
        case .RingtoneDucked_US_Haptic: return 1491
        case .RingtoneDucked_UK_Haptic: return 1492
        case .SalientNotification_Haptic: return 1493
        case .Notification_Salient_Haptic: return 1494
        case .ET_BeginNotification_Salient_Haptic: return 1495
        case .Alert_Calendar_Salient_Haptic: return 1496
        case .Alert_ReminderDue_Salient_Haptic: return 1499
        case .Alert__3rdParty_Salient_Haptic: return 1501
        case ._3rdParty_DirectionUp_Haptic: return 1502
        case ._3rdParty_DirectionDown_Haptic: return 1503
        case ._3rdParty_Success_Haptic: return 1504
        case ._3rdParty_Failure_Haptic: return 1505
        case ._3rdParty_Retry_Haptic: return 1506
        case ._3rdParty_Start_Haptic: return 1507
        case ._3rdParty_Stop_Haptic: return 1508
        case .Alarm_Nightstand_Haptic: return 1509
        case .Alert_BatteryLow_5p_Salient_Haptic: return 1510
        case .NavigationLeftTurn_Salient_Haptic: return 1511
        case .NavigationRightTurn_Salient_Haptic: return 1512
        case .NavigationGenericManeuver_Salient_Haptic: return 1513
        case .SedentaryTimer_Salient_Haptic: return 1514
        case .Alert_ActivityGoalAttained_Salient_Haptic: return 1515
        case .Alert_ActivityGoalBehind_Salient_Haptic: return 1516
        case .Alert_PassbookGeofence_Salient_Haptic: return 1517
        case .WorkoutSaved_Haptic: return 1518
        case .VoiceOver_Click_Haptic: return 1522
        case .SiriAutoSend_Haptic: return 1523
        case .HummingbirdCompletion_Haptic: return 1525
        case .HummingbirdNotification_Haptic: return 1526
        case .RemoteCameraShutterBurstBegin_Haptic: return 1527
        case .RemoteCameraShutterBurstEnd_Haptic: return 1528
        case .WorkoutPaused_Haptic: return 1529
        case .WorkoutResumed_Haptic: return 1530
        case .GoToSleep_Haptic: return 1531
        case .Warsaw_Haptic: return 1532
        case .AutoUnlock_Haptic: return 1533
        case .Alert_ActivityFriendsGoalAttained_Haptic: return 1534
        case .Alert_SpartanConnecting_Haptic: return 1535
        case .Alert_SpartanConnecting_LowLatency_Haptic: return 1536
        case .Alert_SpartanConnected_LowLatency_Haptic: return 1537
        case .Alert_SpartanDisconnected_LowLatency_Haptic: return 1538
        case .AccessScanComplete_Haptic: return 1543
        case .BuddyMigrationStart_Haptic: return 1544
        case .SOSFallDetectionPrompt_Haptic: return 1545
        case .SOSEmergencyContactTextPrompt_Haptic: return 1546
        case .WorkoutStartAutodetect: return 1547
        case .WorkoutCompleteAutodetect: return 1548
        case .WorkoutPausedAutoDetect: return 1549
        case .WorkoutResumedAutoDetect: return 1550
        case .WorkoutPaceAbove: return 1551
        case .WorkoutPaceBelow: return 1552
        case .WalkieTalkieReceiveStart_Haptic: return 1553
        case .WalkieTalkieReceiveEnd_Haptic: return 1554
        case .Alert_Health_Haptic: return 1555
        case .MultiwayInvitation: return 1558
        case ._3rd_Party_Critical_Haptic: return 1559
        case .Alert_1stParty_Haptic: return 1560
        case .Siren_Countdown_Major_Haptic: return 1563
        case .Siren_Countdown_Minor_Haptic: return 1564
        case .Doorbell_Haptic: return 1566
        case .System_Notification_Haptic: return 1567
        case .SOSFallDetectionPromptEscalation_Haptic: return 1568
        case .HealthReadingComplete_Haptic: return 1570
        case .HealthReadingFail_Haptic: return 1571
        case .WorkoutPrecisionStart_Haptic: return 1581
        case .IntervalEnded: return 1582
        case .IntervalUpcoming: return 1583
        case .Elevation: return 1584
        default: return 0
        }
    }
}
