//
//  SystemSound.swift
//  system-sound
//
//  Created by otake on 2025/05/11.
//

import Foundation
import AudioToolbox

public enum SystemSound {
    case ringback_tone_ansi
    case ringback_tone_cept
    case busy_tone_ansi
    case busy_tone_cept
    case call_waiting_tone_ansi
    case call_waiting_tone_cept
    case end_call_tone_cept
    case ringback_tone_hk
    case ringback_tone_aus
    case ringback_tone_uk
    case new_mail
    case mail_sent
    case sms_received1
    case ReceivedMessage
    case SentMessage
    case alarm
    case low_power
    case sms_received2
    case sms_received3
    case sms_received4
    case sms_received5
    case sms_received6
    case tweet_sent
    case Swish
    case Anticipate
    case Bloom
    case Calypso
    case Choo_Choo
    case Descent
    case Fanfare
    case Ladder
    case Minuet
    case News_Flash
    case Noir
    case Sherwood_Forest
    case Spell
    case Suspense
    case Telegraph
    case Tiptoes
    case Update
    case ussd
    case SIMToolkitCallDropped
    case SIMToolkitGeneralBeep
    case SIMToolkitNegativeACK
    case SIMToolkitPositiveACK
    case SIMToolkitSMS
    case Tink
    case WebcamStart
    case ct_busy
    case ct_congestion
    case ct_path_ack
    case ct_error
    case ct_call_waiting
    case ct_keytone2
    case lock
    case key_press_click
    case Tock
    case connect_power
    case RingerChanged
    case photoShutter
    case shake
    case jbl_begin
    case jbl_confirm
    case jbl_cancel
    case begin_record
    case end_record
    case jbl_ambiguous
    case jbl_no_match
    case camera_shutter_burst
    case airdrop_invite
    case camera_shutter_burst_begin
    case camera_shutter_burst_end
    case focus_change_keyboard
    case focus_change_app_icon
    case focus_change_large
    case focus_change_small
    case navigation_push
    case navigation_pop
    case keyboard_press_normal
    case keyboard_press_delete
    case keyboard_press_clear
    case vc_invitation_accepted
    case vc_ringing
    case vc_ended
    case key_press_delete
    case key_press_modifier
    case wheels_of_time
    case go_to_sleep_alert
    case warsaw
    case nfc_scan_complete
    case access_scan_complete
    case _3rd_party_critical
    case PaymentReceived
    case Doorbell
    case PaymentReceivedFailure
    case dtmf_0
    case dtmf_1
    case dtmf_2
    case dtmf_3
    case dtmf_4
    case dtmf_5
    case dtmf_6
    case dtmf_7
    case dtmf_8
    case dtmf_9
    case dtmf_star
    case dtmf_pound
    case DeviceShutdown
    case long_low_short_high
    case short_double_high
    case short_low_high
    case short_double_low
    case middle_9_short_double_low
    case camera_timer_final_second
    case camera_timer_countdown
    case health_notification
    case MultiwayJoin
    case MultiwayLeave
    case multiway_invitation
    case PushToTalkJoined
    case PushToTalkLeft
    case PushToTalkUnmute
    case PushToTalkMute
    case PushToTalkUnmuteFail
    case SenderConfirmation
    case ReceiverConfirmation
    case ReceiverConnect
    case Typewriters
    case PINEnterDigit_AX
    case PINDelete_AX
    case PINSubmit_AX
    case PINUnexpected
    case PINEnterDigit
    case PINDelete
    case HeadphoneAudioExposureLimitExceeded
    case HealthNotificationUrgent
    case MicMute
    case MicUnmute
    case MicUnmuteFail
    case ScreenSharingStarted
    case MediaPaused
    case MediaHandoff
    case NavigationGenericManeuver
    case ScreenCapture
    case payment_success
    case payment_failure
    case acknowledgment_sent
    case acknowledgment_received
    case nfc_scan_failure
    case Notification_Haptic
    case Ringtone_US_Haptic
    case Ringtone_UK_Haptic
    case Alarm_Haptic
    case SiriStart_Haptic
    case SiriStopSuccess_Haptic
    case SiriStopFailure_Haptic
    case Stockholm_Haptic
    case Beat_Haptic
    case DoNotDisturb_Haptic
    case Timer_Haptic
    case NavigationLeftTurn_Haptic
    case NavigationRightTurn_Haptic
    case Detent_Haptic
    case NavigationGenericManeuver_Haptic
    case CameraCountdownTick_Haptic
    case CameraCountdownImminent_Haptic
    case ET_RemoteTap_Receive_Haptic
    case ET_RemoteTap_Send_Haptic
    case ET_BeginNotification_Haptic
    case StockholmActive_Haptic
    case StockholmActiveSingleCycle_Haptic
    case StockholmFailure_Haptic
    case SedentaryTimer_Haptic
    case HourlyChime_Haptic
    case Preview_AudioAndHaptic
    case Alert_ActivityGoalAttained_Haptic
    case Alert_ActivityGoalBehind_Haptic
    case Alert_ActivityGoalClose_Haptic
    case Alert_BatteryLow_10p_Haptic
    case Alert_BatteryLow_5p_Haptic
    case Alert_Calendar_Haptic
    case Alert_PassbookBalance_Haptic
    case Alert_PassbookGeofence_Haptic
    case Alert_PhotostreamActivity_Haptic
    case Alert_ReminderDue_Haptic
    case Alert_WalkieTalkie_Haptic
    case BatteryMagsafe_Haptic
    case BuddyPairingFailure_Haptic
    case BuddyPairingSuccess_Haptic
    case CameraShutter_Haptic
    case Alert_MapsDirectionsInApp_Haptic
    case MessagesIncoming_Haptic
    case MessagesOutgoing_Haptic
    case OnOffPasscodeFailure_Haptic
    case OrbLayers_Haptic
    case PhoneHangUp_Haptic
    case PhotosZoomDetent_Haptic
    case QB_Dictation_Haptic
    case StopwatchLap_Haptic
    case StopwatchReset_Haptic
    case StopwatchStart_Haptic
    case StopwatchStop_Haptic
    case TimerCancel_Haptic
    case TimerPause_Haptic
    case TimerStart_Haptic
    case TimerWheelHoursDetent_Haptic
    case WalkieTalkieActiveStart_Haptic
    case WorkoutComplete_Haptic
    case WorkoutCountdown_Haptic
    case Alert__3rdParty_Haptic
    case WorkoutSelect_Haptic
    case WorkoutPressStart_Haptic
    case TimerWheelMinutesDetent_Haptic
    case PhoneAnswer_Haptic
    case PhoneHold_Haptic
    case WalkieTalkieActiveEnd_Haptic
    case UISwitch_On_Haptic
    case UISwitch_Off_Haptic
    case UISwipe_Haptic
    case SystemStartup_Haptic
    case BuddyPairingRemoteConnection_Haptic
    case BuddyPairingRemoteTap_Haptic
    case QB_Dictation_Off_Haptic
    case RingtoneDucked_US_Haptic
    case RingtoneDucked_UK_Haptic
    case SalientNotification_Haptic
    case Notification_Salient_Haptic
    case ET_BeginNotification_Salient_Haptic
    case Alert_Calendar_Salient_Haptic
    case Alert_ReminderDue_Salient_Haptic
    case Alert__3rdParty_Salient_Haptic
    case _3rdParty_DirectionUp_Haptic
    case _3rdParty_DirectionDown_Haptic
    case _3rdParty_Success_Haptic
    case _3rdParty_Failure_Haptic
    case _3rdParty_Retry_Haptic
    case _3rdParty_Start_Haptic
    case _3rdParty_Stop_Haptic
    case Alarm_Nightstand_Haptic
    case Alert_BatteryLow_5p_Salient_Haptic
    case NavigationLeftTurn_Salient_Haptic
    case NavigationRightTurn_Salient_Haptic
    case NavigationGenericManeuver_Salient_Haptic
    case SedentaryTimer_Salient_Haptic
    case Alert_ActivityGoalAttained_Salient_Haptic
    case Alert_ActivityGoalBehind_Salient_Haptic
    case Alert_PassbookGeofence_Salient_Haptic
    case WorkoutSaved_Haptic
    case VoiceOver_Click_Haptic
    case SiriAutoSend_Haptic
    case HummingbirdCompletion_Haptic
    case HummingbirdNotification_Haptic
    case RemoteCameraShutterBurstBegin_Haptic
    case RemoteCameraShutterBurstEnd_Haptic
    case WorkoutPaused_Haptic
    case WorkoutResumed_Haptic
    case GoToSleep_Haptic
    case Warsaw_Haptic
    case AutoUnlock_Haptic
    case Alert_ActivityFriendsGoalAttained_Haptic
    case Alert_SpartanConnecting_Haptic
    case Alert_SpartanConnecting_LowLatency_Haptic
    case Alert_SpartanConnected_LowLatency_Haptic
    case Alert_SpartanDisconnected_LowLatency_Haptic
    case AccessScanComplete_Haptic
    case BuddyMigrationStart_Haptic
    case SOSFallDetectionPrompt_Haptic
    case SOSEmergencyContactTextPrompt_Haptic
    case WorkoutStartAutodetect
    case WorkoutCompleteAutodetect
    case WorkoutPausedAutoDetect
    case WorkoutResumedAutoDetect
    case WorkoutPaceAbove
    case WorkoutPaceBelow
    case WalkieTalkieReceiveStart_Haptic
    case WalkieTalkieReceiveEnd_Haptic
    case Alert_Health_Haptic
    case MultiwayInvitation
    case _3rd_Party_Critical_Haptic
    case Alert_1stParty_Haptic
    case Siren_Countdown_Major_Haptic
    case Siren_Countdown_Minor_Haptic
    case Doorbell_Haptic
    case System_Notification_Haptic
    case SOSFallDetectionPromptEscalation_Haptic
    case HealthReadingComplete_Haptic
    case HealthReadingFail_Haptic
    case WorkoutPrecisionStart_Haptic
    case IntervalEnded
    case IntervalUpcoming
    case Elevation
    case Alert_Voicemail_Haptic
    case Alert_Voicemail_Salient_Haptic
    case EarInteraction_Complete
    case HeadGesturesDoubleNod
    case HeadGesturesDoubleShake
    case HeadGesturesPartialNod
    case HeadGesturesPartialShake
    case _jbl_begin
    case _jbl_begin_short
    case jbl_begin_short
    case jbl_begin_short_carplay
    case _jbl_cancel
    case _jbl_confirm
    case LiquidDetected
    case NanoAlert10
    case NanoAlert10_Prominent
    case NanoAlert2
    case NanoAlert2_Prominent
    case NanoAlert3
    case NanoAlert3_Prominent
    case NanoAlert4
    case NanoAlert4_Promiment
    case NanoAlert5
    case NanoAlert5_Prominent
    case NanoAlert6
    case NanoAlert6_Prominent
    case NanoRingtone3
    case NanoRingtone4
    case NanoRingtone6
    case NFCCardComplete
    case NFCCardError
    case NFCCardProvisioned
    case OnOffPasscodeUnlock_Haptic
    case OnOffPasscodeUnlockCampanion_Haptic
    case OrbExit_Haptic
    case RemoteAttentionRequest_Alert
    case Ringtone_2_Ducked_Haptic_sashimi
    case Ringtone_2_Haptic_sashimi
    case _sms_received1
    case vc_ringing_watch
    case WalkAMile_Haptic
}
